version: '2'

services:
  activemq:
    image: rmohr/activemq:5.14.3
    container_name: activemq
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
    networks:
      - default